####################################
# Central Configuration                                    #
####################################

lang: en_us

#afktime: AFKになるまでの時間
#afkkick: AFKKicktimeで指定した時間に
afktime: 120
afkkicktime: 300
afkkick: false
