name: Central
main: net.shiroumi.central.CentralCore
version: 0.1
authors: [Laica-Lunasys, squarepp2]
commands:
  afk: 
  clear: 
  gm: 
  give: 
  home:
  inv: 
  item: 
  nopickup: 
    aliases: np
  spawn: 
  thor: 
  ban: 
  broadcast: 
    aliases: bc
  kick: 
  lockdown: 
  onlineplayers: 
  time: 
  weather: 
