name: Central
main: net.shiroumi.central.CentralCore
version: 0.1
authors: [Laica-Lunasys, squarepp2]
commands:
<<<<<<< HEAD
  afk: 
  clear: 
  gm: 
  give: 
  home:
  inv: 
  item: 
  nopickup: 
  spawn: 
  thor: 
  ban: 
  broadcast: 
  kick: 
  lockdown: 
  onlineplayers: 
  time: 
  weather: 
  
=======
  gm:
  invisible:
  spawn:
  setspawn:
  home:
  sethome:
  thor:
  nopickup:
  item:
  afk:
  kick:
  ban:
  broadcast:
  who:
  time:
  weather:
  clear:
  lock:
>>>>>>> branch 'master' of https://github.com/Laica-Lunasys/Central.git
